#!/usr/bin/env python3

import subprocess
import os

out=subprocess.check_output(["git", "status"])

out=out.decode("utf-8")
out=out.split("\n")

for item in out:
    if "modified:" in item:
        item=item.replace("modified:","")
        item=item.replace(" ","")
        item=item.replace("\t","")
        #os.system('C:/Program\ Files/Git/git add '+item)
        subprocess.call(["git","add",item])
        print(item)
    elif "deleted:" in item:
        item=item.replace("deleted:","")
        item=item.replace(" ","")
        item=item.replace("\t","")
        #os.system('C:/Program\ Files/Git/git add '+item)
        subprocess.call(["git","add",item])
        print(item)
    elif "\t" in item:
        item=item.replace(" ","")
        item=item.replace("\t","")
        #os.system('C:/Program\ Files/Git/git add '+item)
        subprocess.call(["git","add",item])
        print(item)

subprocess.call(["git","commit","-m","\"Update Files\""])
#os.system('C:/Program\ Files/Git/git commit -m \"Update Files\"')
subprocess.call(["git","push","origin","master"])
#os.system('C:/Program\ Files/Git/git push origin master')

