#!/usr/bin/env python3

import subprocess
import os

proc = subprocess.Popen(["git status"], stdout=subprocess.PIPE, shell=True)
(out, err) = proc.communicate()
out=out.decode("utf-8")
out=out.split("\n")
for item in out:
    if "modified:" in item:
        item=item.replace("modified:","")
        item=item.replace(" ","")
        item=item.replace("\t","")
        os.system('git add '+item)
        #print(item)
    elif "deleted:" in item:
        item=item.replace("deleted:","")
        item=item.replace(" ","")
        item=item.replace("\t","")
        os.system('git add '+item)
        #print(item)
    elif "\t" in item:
        item=item.replace(" ","")
        item=item.replace("\t","")
        os.system('git add '+item)
        #print(item)

os.system('git commit -m \"Update Files\"')
os.system('git push origin master')

