#!/usr/bin/env python3

################################################################
##################### Import packages ##########################
################################################################

import numpy as np
import matplotlib.pyplot as plt
import time
start_time = time.time()
from scipy.stats import multivariate_normal

import Functions as fun

################################################################
###################### Calculations ############################
################################################################

u=np.zeros(2500)

k=np.zeros((2500,2500))

for i in range(0,50):
    print(i)
    for j in range(0,50):
        for l in range(0,50):
            for m in range(0,50):
                k[i*50+l,j*50+m] = np.exp(-np.abs(i/50.0-j/50.0)-np.abs(l/50.0-m/50.0))

for m in range(1,5):
    U=multivariate_normal.rvs(u,k)
    Z = [[U[50*i+j] for j in range(0,50)] for i in range(0,50)]
    plt.imshow(Z, extent=(0,1,0,1))
    plt.savefig("P1realization"+str(m)+".pdf")

###################### Time To execute #################

print("--- %s seconds ---" % (time.time() - start_time))
