#!/usr/bin/env python3

################################################################
##################### Import packages ##########################
################################################################

import time
start_time = time.time()
import FUN as fun


x=5;NumofC=10
alpha=10-1;beta=1/0.1

################################################################
############### Deterministic Calculations #####################
################################################################

cn=[]
for n in range(0,NumofC):
    cn.append(fun.Determine_cn(n,alpha,beta,x))

Var=0
for n in range(1,NumofC):
    Coef=fun.gammaf(n+alpha+1)/(fun.gammaf(alpha+1)*fun.fact(n))
    Var=Var+Coef*(cn[n]**2)


###################### Time To execute #################

print("--- %s seconds ---" % (time.time() - start_time))
