#!/usr/bin/env python3

################################################################
##################### Import packages ##########################
################################################################

import time
start_time = time.time()
import FUN as fun


x=fun.np.linspace(0,10,100);alpha=1;beta=2;NumofC=10
alpha=10-1;beta=1/0.1

y=[];Variance=[]
for i in range(0,len(x)):
################################################################
############### Deterministic Calculations #####################
################################################################
    print(x[i])
    cn=[]
    for n in range(0,NumofC):
        cn.append(fun.Determine_cn(n,alpha,beta,x[i]))

    Var=0
    for n in range(1,NumofC):
        Coef=fun.gammaf(n+alpha+1)/(fun.gammaf(alpha+1)*fun.fact(n))
        Var=Var+Coef*(cn[n]**2)

    y.append(cn[0])
    Variance.append(Var)

################################################################
################## Printing and Plotting #######################
################################################################

#Plot the data, and plot fitted PDF
fun.Plot(x,y,Variance,'mean.pdf','linear')
fun.Plot(x,y,Variance,'meanlog.pdf','log')

###################### Time To execute #################

print("--- %s seconds ---" % (time.time() - start_time))
