#!/usr/bin/env python3

################################################################
##################### Import packages ##########################
################################################################

import os.path
import pandas as pd
import datetime
from uncertainties import ufloat
from uncertainties.umath import *
from uncertainties import unumpy as unp
import re
import time
start_time = time.time()

import Functions as fun

################################################################
######################## Calculations ##########################
################################################################
import scipy.special as sps
import numpy as np
import matplotlib.pyplot as plt

N=100
alpha=1
beta=0.5

theta=np.linspace(0,20,N)
f_x=((theta**(alpha-1))*np.exp(-theta/beta))\
               /\
    (sps.gamma(alpha)*beta**(-alpha))

plt.plot(theta,f_x,'r')
plt.show()

#######################################################
############ Atom Fraction to Mass Fraction ###########
############          and vice versa        ###########
#######################################################


###################### Time To execute #################

print("--- %s seconds ---" % (time.time() - start_time))
