#!/usr/bin/env python3

################################################################
##################### Import packages ##########################
################################################################

import numpy as np
import matplotlib.pyplot as plt
import time
start_time = time.time()
from scipy.stats import norm

################################################################
###################### Calculations ############################
################################################################

N=1000
Nbins=30
RandomNumbers=np.random.uniform(low=0,high=1,size=N)

#Sample the inverse of the CDF of the standard normal
#distribution
Samples=norm.ppf(RandomNumbers)

#Generate histogram
fig=plt.figure()
ax=fig.add_subplot(111)
ax.set_xlabel('Normal Sampling',fontsize=16)
ax.set_ylabel('Count out of '+str(N),fontsize=18)
ax.hist(Samples,Nbins,color='green',alpha=0.7,edgecolor='black')
#ax.set_xlim(-500,500)
plt.savefig("NNorm.pdf")
                            

#Strat sampling...



###################### Time To execute #################

print("--- %s seconds ---" % (time.time() - start_time))
