#!/usr/bin/env python3

################################################################
##################### Import packages ##########################
################################################################

import time
start_time = time.time()
import Functions as fun


################################################################
###################### Calculations ############################
################################################################

N=10000  #Samples
Nbins=100 #Hist Plot
Nstrata=1000
filename="Histf.pdf"

Xlabel="Stratified Sampling both samples"
RandomNumbersX=fun.Rstrat(N,Nstrata)
RandomNumbersY=fun.Rstrat(N,Nstrata)

Samplest=fun.beta.ppf(RandomNumbersX,3,2)
Sampless=fun.beta.ppf(RandomNumbersY,1.1,2)

X=fun.X(Samplest)
Y=fun.Y(Sampless)

f=fun.Rosen(X,Y)

Xlabel="Rosenbrock Function Histogram"
fun.HIST(Xlabel,f,Nbins,filename,N)


PGreater=sum(i<10 for i in f)/N

print("The probability of being less than 10 is: "+str(PGreater[0]))

                            
###################### Time To execute #################

print("--- %s seconds ---" % (time.time() - start_time))
