#!/usr/bin/env python3

################################################################
##################### Import packages ##########################
################################################################

import time
start_time = time.time()
import Functions as fun


################################################################
###################### Calculations ############################
################################################################

N=10000  #Samples
Nbins=200 #Hist Plot
Nstrata=1000
filename="Histf.pdf"

Xlabel="Stratified Sampling both samples"
RandomNumbersX=fun.Rstrat(N,Nstrata)
RandomNumbersY=fun.Rstrat(N,Nstrata)

Samplest=fun.beta.ppf(RandomNumbersX,3,2)
Sampless=fun.beta.ppf(RandomNumbersY,1.1,2)

ut=fun.betau(3,2)
us=fun.betau(1.1,2)
ot=fun.betao(3,2)
os=fun.betao(1.1,2)
ux=fun.X(ut)
uy=fun.Y(us)


print("X mean is "+str(ux))
print("Y mean is "+str(uy))
print("X sig is "+str((ot**0.5)*2))
print("Y sig is "+str((os**0.5)*2))
print("Mean Z is "+str(fun.Z())
quit()

X=fun.X(Samplest)
Y=fun.Y(Sampless)

f=fun.Rosen(X,Y)

Xlabel="Rosenbrock Function Histogram"
(I)=fun.HIST(Xlabel,f,Nbins,filename,N)

PGreater=sum(i<10 for i in f)/N

print("The probability of being less than 10 is: "+str(PGreater[0]))




###################### Time To execute #################

print("--- %s seconds ---" % (time.time() - start_time))
