#!/usr/bin/env python3

################################################################
##################### Import packages ##########################
################################################################

import time
start_time = time.time()
import Functions as fun
import numpy as np
import pandas as pd

################################################################
###################### Calculations ############################
################################################################

Df=pd.read_csv('output')
Vars=['v','D','w','dt','dx']
Df2=Df[Vars]
model=pd.ols(y=Df['RXNRate'],x=Df2)

print(model.summary().as_latex())

###################### Time To execute #################

print("--- %s seconds ---" % (time.time() - start_time))
