#!/usr/bin/env python3

################################################################
##################### Import packages ##########################
################################################################
import numpy as np
import time
import copy
import scipy.special as sps
import matplotlib.pyplot as plt
plt.rcParams["font.family"] = "monospace"
import matplotlib
matplotlib.rc('text',usetex=True)
matplotlib.rcParams['text.latex.preamble']=[r"\usepackage{amsmath}"]
start_time = time.time()
################################################################
##################### Calculations #############################
################################################################

fig=plt.figure()
ax=fig.add_subplot(111)
ax.set_xlabel(r'$\boldsymbol{x}$',fontsize=18)
ax.set_ylabel(r'\textbf{y}',fontsize=18)
ax.grid(alpha=0.8,color='black',linestyle='dotted')

B=3.826659

for i in range(0,10):

    l1=np.random.uniform(0,1)
    l2=np.random.uniform(0,1)

    U=(1-l2)**B
    Us=(1-l2)**(B-1)

    error=100

    count=0
    V=(1-l1)**B
    while(error>0.001):
        A=(V-U*(V-1))**((1/B)-1)
        C=l1/Us
        Vn=1-C/A
        error=abs(V-Vn)/Vn
        V=copy.copy(Vn)
    
        if count>999:
            print("Did not converge after 1000")
            quit()
        count=count+1
    W=1-V**(1/B)
    print(W)
    x=(2**0.5)*sps.erfinv(2*l1-1)
    y=(2**0.5)*sps.erfinv(2*W-1)
    ax.plot(x,y,'ko',markersize=5)

plt.savefig('P5.pdf')
