#!/usr/bin/env python3

################################################################
##################### Import packages ##########################
################################################################

import time
start_time = time.time()
import scipy.special as sps
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import random as rn
import Functions as fun
import copy

################################################################
######################## Calculations ##########################
################################################################

N=np.array([10,100,1000,10000])


for i in range(0,len(N)):
    s=np.random.normal(0,1,N[i])
    mean=sum(s)/N[i]
    variance=(1/N[i])*sum((s-mean)**2)
    skew=(1/N[i])*sum((s-mean)**3)/((variance)**(3/2))
    kurtosis=(1/N[i])*sum((s-mean)**4)/(variance**2)-3
    #variance=sum(variance)
    #print("N = "+str(N[i])+" variance = "+str(variance))
    print(kurtosis)

    
###################### Time To execute #################
print("--- %s seconds ---" % (time.time() - start_time))
