#!/usr/bin/env python3

#########################################################################
######################## Import Packages ################################
#########################################################################

import time
start_time = time.time()
import Functions as f
from scipy import interpolate
from scipy import integrate
from scipy.integrate import trapz
import os

#########################################################################
########################## Calculations #################################
#########################################################################

#########################################################
############### Import X-Section Data ###################
#########################################################

#Get list of csv files with X-section information
Names=f.GETcsvFiles(".")


#Loop through all the X-sections I got
#Find the ones with Lin-Lin in them
#And modify...
for Name in Names:
    with open(Name) as f:
        content=f.readlines()

    if "Lin-Lin" in content[0]:
        #Open output file
        output=open(Name+'.copy',"w")
        for i in content:
            #Modify line
            i=i.replace('Lin-Lin','').split()
            i[0]=str(float(i[0])*10**(-6))
            i=",".join(i)
            #Print to output
            print(i,file=output)
        os.system("mv "+Name+'.copy '+Name)


    
#########################################################################
######################## Time to Execute ################################
#########################################################################

print("--- %s seconds ---" % (time.time() - start_time))
