#!/usr/bin/env python3

############################################################
############### Import Packages ############################
############################################################


import requests
from bs4 import BeautifulSoup

############################################################
#################### Open Link #############################
############################################################

#Might have to update these URLs
url_to_scrape='http://www.nndc.bnl.gov/exfor/servlet/X4sShowData?File=E4R8176_e4.zvd'

#not sure what these two lines do, but it
#gets all the information from the URL, and saves
#it in a soup type...thingy
r = requests.get(url_to_scrape)
soup = BeautifulSoup(r.text,"lxml")

#Find the index of our starting point
x=soup.prettify().find('xx:\n')+4
print(x)

#Save all the information in a long list
LongList=soup.prettify()[x:-1].split('\n')

print(len(LongList))

#open the output file
#output=open('U_235_92_cov',"w")

#Modify the data, and store in file
for i in range(0,len(LongList)-1):
        if i<4:
                print(LongList[i])
        #Data=LongList[i].split()
        #Data[0]=str(float(Data[0])*1e-6)
        #print(",".join(Data),file=output)
