#!/usr/bin/env python3

#########################################################################
######################## Import Packages ################################
#########################################################################

from bs4 import BeautifulSoup as bs
import urllib.request

#Link to read data from

Link='http://www.nndc.bnl.gov/exfor/servlet/X4sGetTabData?datfile=E4R21219_tdat.dat&emin=1e-05&emax=2e%2B07'


#Open link?
with urllib.request.urlopen(Link) as url:
        html = url.read()
#Save in soup?
soup = bs(html, 'html.parser')
texts = soup.findAll(text=True)


List=html.split('\r\n')
print(len(List))
