#!/usr/bin/env python3

################################################################
##################### Import packages ##########################
################################################################

import time
start_time = time.time()
import scipy.special as sps
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import Functions as fun

################################################################
######################## Calculations ##########################
################################################################

N=100
#Can't use 0 in some calculations below, because division by zero
notzero=0.000001

x=np.linspace(0,8,N)
y=np.linspace(notzero,2**0.5,N)
ux=0.942809
uy=0.942809

f_X=np.exp(-x/uy)/uy

C=(2**0.5)*np.exp(-ux/(2**0.5))
#Note gammaincc has two c values
C2=ux*sps.gammaincc(notzero,ux/(2**0.5))*sps.gamma(notzero)
f_Y=np.exp(-ux/y)/(C-C2)

fig,ax=fun.Plot()

ax=fun.Plotax(x,f_X,ax,2)

ax=fun.Plotax(y,f_Y,ax,1)

plt.savefig('P10F1.pdf')

###################### Time To execute #################
print("--- %s seconds ---" % (time.time() - start_time))
