#!/usr/bin/env python3

#Please note, might have to run command
# sed -i 's/E /E\+/g' TAPE9_BANK.inp
# on file to make sure there are no spaces after E's

#####################################################################
######################## Import Packages ############################
#####################################################################

import time
start_time = time.time()
import numpy as np
import Functions as Fun
from subprocess import call


#Graboutput print to file
t=Fun.Graboutput("CS137")

    
#####################################################################
######################## Time to Execute ############################
#####################################################################

print("--- %s seconds ---" % (time.time() - start_time))

